########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input
intermediate_dir:     intermediate
output_dir:           output
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake


####################################
# COMPRESSION PROTOCOLS TO INCLUDE #
####################################

# Protocol 1: compr. of genome assemblies
protocol_asm:         True

# Protocol 2: compr. of dBGs (w/o k-mer propagation; pre-propagation simplitigs)
protocol_pre:         False

# Protocol 3: compr. of dBGs (w/ k-mer propagation; post-propagation simplitigs)
protocol_post:        False


############################
# DATA ANALYSES TO INCLUDE #
############################

# Calculate #seqs and their cumulative length
sequence_statistics:  True

# Include analyses based on k-mer counts (using JellyFish 2)
kmer_statistics:      False


##############
# PARAMETERS #
##############

# (1) General parameters; notes:
#     - kmer length defines k for dBGs in Protocols 2 and 3
#     - the same k-mer length is used also for k-mer counting (all protocols)
#     - converting sequences to upper case is used in Protocol 1
kmer_length:          31
asms_to_uppercase:    True


# (2) XZ parameters; notes:
#     - best compression is always achieved with 1 thread
#     - increasing xz_threads is useful for acceleration, but the files get >2x bigger
#     - for all XZ params, see 'man xz'
xz_threads:           1
xz_params:            "-9"


# (3) Mashtree parameters; notes:
#     - sketch size should be at least 10k to achieve a sufficient resolution
mashtree_threads:     8
mashtree_kmer_length: 21
mashtree_sketch_size: 10000

# (4) Jellyfish parameters
jellyfish_threads:    8
jellyfish_size:       "40M"

