########################################################################################################################
# input configuration
# This parameter denotes the input dir, a path to a directory with a very specific structure, that contains the input
#     data to this pipeline, i.e. the batches.
# Here we describe this structure in details.
# Each batch named <batch> is composed of one required file (<batch>.txt) and one optional file (<batch>.nw).
#   * The <batch.txt> file is a text file where each line is a path to an assembly file;
#      * An assembly file is a file with extensions ["fa", "fasta", "fna", "ffa"], optionally compressed with gzip
#          ("gz" extension) denoting the assembly of a sample;
#      * Every *.txt file in the input dir will be interpreted as a batch;
#      * See .test/input/test_run_with_tree.txt for an example of a <batch>.txt file;
#   * The <batch>.nw is an optional newick file representing the tree of the samples in its respective <batch>.txt
#          file. If this file is not provided, this pipeline builds a tree automatically using Mashtree.
#   * These files must be at the top level of the given directory.
input_dir: input
output_dir: output
########################################################################################################################


########################################################################################################################
# output configuration
generate_assembly_stats: True  # True or False
generate_prepropagation_stats: True  # True or False
generate_postpropagation_stats: True  # True or False
########################################################################################################################
