###############
# DIRECTORIES #
###############

input_dir:            input
intermediate_dir:     intermediate
output_dir:           output


#####################################
# COMPRESSION / ANALYSES TO INCLUDE #
#####################################

# Protocol 1: compr. of asms
protocol_asm:         True

# Protocol 2: compr. of dbgs (w/o k-mer propagation)
protocol_pre:         False

# Protocol 3: compr. of dbgs (w/ k-mer propagation)
protocol_post:        False


# additional data analyses
nscl_analyses:        True   # include #seqs, their cum. leng. stats
kmer_counting:        False  # include k-mer counting analyses


##############
# PARAMETERS #
##############

kmer_length:          31     # used in Protocols 2 and 3 for dbgs, and for k-mer counting
asms_to_uppercase:    True   # used in Protocol 1

xz_threads:           1      # best compression with 1, can be increased for accelarating testing
xz_params:            "-9"   # additional params for xz can be added here

mashtree_threads:     8
mashtree_kmer_length: 21
mashtree_sketch_size: 10000

jellyfish_threads:    8
