name: Tests

on:
  push:
    branches:
      - master
      - reproducibility
  pull_request:
    branches_ignore: []

jobs:
  #Linting:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Lint workflow
  #    uses: snakemake/snakemake-github-action@v1.5.3
  #    with:
  #      directory: .
  #      snakefile: workflow/Snakefile
  #      args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    #needs: Linting
    steps:
    - uses: actions/checkout@v3
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        snakefile: workflow/Snakefile
        args: "-j 4 --use-conda -p --show-failed-logs --conda-cleanup-pkgs"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        snakefile: workflow/Snakefile
        args: "--use-conda --report test_report.html"
