name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Testing:
    runs-on: ${{ matrix.os }}

    continue-on-error:  true

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.9", "3.10" ]
        snakemake-version: [ "6", "7" ]
        include:
          - python-version: "3.8"
            snakemake-version: "7"
          - python-version: "3.9"
            snakemake-version: "7"
          - python-version: "3.10"
            snakemake-version: "7"
          - python-version: "3.11"
            snakemake-version: "7"
          - python-version: "3.11"
            snakemake-version: "8"
          - python-version: "3.11"
            snakemake-version: "8.0"
          - python-version: "3.11"
            snakemake-version: "8.1"
          - python-version: "3.11"
            snakemake-version: "8.2"
          - python-version: "3.11"
            snakemake-version: "8.3"
          - python-version: "3.11"
            snakemake-version: "8.4"
          - python-version: "3.11"
            snakemake-version: "8.5"

    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          environment-name: test-env
          condarc: |
            channels:
              - conda-forge
              - bioconda
              - defaults
          create-args: >-
            python=${{ matrix.python-version }}
            snakemake-minimal=${{ matrix.snakemake-version }}
            mamba
            make
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Versions
        shell: bash -el {0}
        run: |
          micromamba activate test-env
          python -v
          snakemake -v
      - name: Make bigtest
        shell: bash -el {0}
        run: |
          micromamba activate test-env
          make bigtest
