name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  #Linting:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Lint workflow
  #    uses: snakemake/snakemake-github-action@v1.5.3
  #    with:
  #      directory: .
  #      snakefile: workflow/Snakefile
  #      args: "--lint"


  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ 3.8, 3.9, "3.10", 3.11 ]
    #needs: Linting
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-name: test-env
          condarc: |
            channels:
              - conda-forge
              - bioconda
              - defaults
          create-args: >-
            python=${{ matrix.python-version }}
            snakemake
            mamba
            make
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Test workflow (local test data)
        shell: bash -el {0}
        run: |
          micromamba activate test-env
          make test
          make testreport
